INSERT INTO maps (creator_id, date_created, name, description) VALUES
(10, '2022-02-08', 'Saint-Genis-Laval, FR, Europe/Paris', 'Evidence best finally body. Base choice couple I house.'),
(5, '2022-02-11', 'Kidodi, TZ, Africa/Dar_es_Salaam', 'Mr close account admit clear. Why child seven smile.'),
(5, '2022-01-28', 'Novelda, ES, Europe/Madrid', 'Conference you two walk market edge physical likely. Test hospital ok explain able consider open road.'),
(1, '2022-01-16', 'Porto Velho, BR, America/Porto_Velho', 'Leader break I everybody family list everybody view. Something million hour bar assume voice.'),
(2, '2022-02-10', 'Carnot, CF, Africa/Bangui', 'Thought physical reality care energy letter president. Assume bag allow huge look.'),
(9, '2022-02-07', 'Iquitos, PE, America/Lima', 'Attack beautiful enter treat.'),
(2, '2022-01-21', 'Sicklerville, US, America/New_York', 'Leader think see establish any bag. To herself whole open.'),
(6, '2022-02-04', 'Bobigny, FR, Europe/Paris', 'Tend church part.'),
(4, '2022-01-17', 'Rosemount, US, America/Chicago', 'Table into number tax grow.'),
(2, '2022-01-26', 'Farafenni, GM, Africa/Banjul', 'Pay more different down event buy.'),
(6, '2022-01-17', 'Kanganpur, PK, Asia/Karachi', 'Some trial push cell see according.'),
(1, '2022-01-31', 'Balikpapan, ID, Asia/Makassar', 'Process majority president with.'),
(10, '2022-01-28', 'Lino Lakes, US, America/Chicago', 'Share national mother would necessary.'),
(9, '2022-01-27', 'Frankston South, AU, Australia/Melbourne', 'Process stuff dinner rich.'),
(7, '2022-01-15', 'Kirchlengern, DE, Europe/Berlin', 'Civil spend stay growth. For general simply remember.'),
(3, '2022-01-31', 'Hushitai, CN, Asia/Shanghai', 'Site window according management team more.'),
(3, '2022-01-16', 'Barras, BR, America/Fortaleza', 'Suggest agreement you wonder party here view.'),
(10, '2022-01-25', 'Rudolstadt, DE, Europe/Berlin', 'Break individual he job throughout blood.'),
(4, '2022-01-21', 'Laiwu, CN, Asia/Shanghai', 'Daughter decade magazine ever here also idea loss. Hit anything where often.'),
(6, '2022-02-11', 'Belle Glade, US, America/New_York', 'Discover decision high someone.'),
(10, '2022-02-05', 'Sungurlu, TR, Europe/Istanbul', 'Detail blue special figure article. Trial from order clear sea.'),
(4, '2022-02-04', 'Shahre Jadide Andisheh, IR, Asia/Tehran', 'Policy allow quality magazine suggest under spend. Animal major ground.'),
(2, '2022-01-14', 'Sungurlu, TR, Europe/Istanbul', 'Entire staff federal college rest. Learn begin they.'),
(10, '2022-01-19', 'Korschenbroich, DE, Europe/Berlin', 'Give tend water play whose structure.'),
(9, '2022-01-17', 'Jaruco, CU, America/Havana', 'Factor anyone everything brother future ball month why. Money realize happy get late.'),
(1, '2022-02-06', 'Lons-le-Saunier, FR, Europe/Paris', 'Agree free shake since century series month.'),
(9, '2022-01-28', 'Elamanchili, IN, Asia/Kolkata', 'Plant people design seem view enough husband. Price per gun economic relate.'),
(8, '2022-02-02', 'Exeter, GB, Europe/London', 'However dog hotel former black. Offer a imagine around employee.'),
(7, '2022-01-29', 'Zeitz, DE, Europe/Berlin', 'Cell election once which tax general couple. From boy little commercial everyone none last.'),
(9, '2022-01-25', 'Halstenbek, DE, Europe/Berlin', 'Help create about building type ground.'),
(6, '2022-01-24', 'Skalica, SK, Europe/Bratislava', 'Art goal the across. Move conference hospital know agency rock now.'),
(4, '2022-01-18', 'Jocotepec, MX, America/Mexico_City', 'Take close will best son language day.'),
(2, '2022-01-24', 'Same, TZ, Africa/Dar_es_Salaam', 'Sort board issue within ahead work military.'),
(6, '2022-02-06', 'Lesnoy, RU, Asia/Yekaterinburg', 'Wall tree international color nice.'),
(8, '2022-02-03', 'Penzance, GB, Europe/London', 'Describe their poor firm pass health local. Certain allow air.'),
(7, '2022-02-08', 'Yashkino, RU, Asia/Novokuznetsk', 'Class community person else someone team build.'),
(5, '2022-01-14', 'Gisborne, NZ, Pacific/Auckland', 'Yes to top me. Test support defense.'),
(5, '2022-01-19', 'Yablonovskiy, RU, Europe/Moscow', 'Drop finally create break. Answer deep top sometimes.'),
(8, '2022-01-24', 'Sheoganj, IN, Asia/Kolkata', 'Nearly join success work. Score although leader reduce they born recognize close.'),
(5, '2022-01-19', 'Rahat, IL, Asia/Jerusalem', 'Professor within second recently before finally. Point pass environment that goal.'),
(10, '2022-02-07', 'Clermont, US, America/New_York', 'Technology wind western. Image wait identify responsibility sense.'),
(10, '2022-01-26', 'Arba Minch, ET, Africa/Addis_Ababa', 'Church today once join.'),
(2, '2022-02-04', 'Hasilpur, PK, Asia/Karachi', 'Material oil special build.'),
(3, '2022-01-16', 'Puducherry, IN, Asia/Kolkata', 'Even support table hundred.'),
(6, '2022-01-22', 'Roseto degli Abruzzi, IT, Europe/Rome', 'Involve add adult war street some mother worry. Girl friend husband group measure shake.'),
(2, '2022-01-23', 'Naushahra Virkan, PK, Asia/Karachi', 'Include peace market inside. Onto ask agree could red begin ask institution.'),
(2, '2022-01-31', 'Dorval, CA, America/Toronto', 'Remain thousand low Republican travel start. Plant small data business civil.'),
(3, '2022-01-29', 'Artur Nogueira, BR, America/Sao_Paulo', 'Figure head interesting really whether real then store.'),
(8, '2022-02-03', 'New Kingston, JM, America/Jamaica', 'Always she young answer avoid. Throw win enter.'),
(10, '2022-01-28', 'Kamakura, JP, Asia/Tokyo', 'Step face father fear economic.');